### ISSUE TITLE
Missing source files

### ISSUE THREAD

**Issue by cmierowsky** [kdavie/yammer.net#1]
I just downloaded the source, and it seems like several cs files are missing, and the solution does not compile. Missing files are:
 Assets.cs, MembershipParameters.cs MessageProperties.cs, PreviousCompany.cs, Relationship.cs, Suggested.cs, Suggestion.cs, UserEducation.cs, UserParameters.cs

**Comment by locuslingua** [comment]
I also noticed this, and the dll compiled with the latest build has issues with Yammer.Auth.GetRequestToken

**Comment by kdavie** [comment]
I've added the missing classes to the repository
