### ISSUE TITLE
Not parsing message topic

### ISSUE THREAD

**Issue by loufranco** [kdavie/yammer.net#2]
Looks to me like you need this

```
public enum ObjectType
{
    NONE,
    MESSAGE,
    USER,
    TAG,
    THREAD,
    GROUP,
    GUIDE,
    TOPIC
}
```

Not sure how to parse a TOPIC.  I am getting a Message Box with a deserialization error

**Comment by ghost** [comment]
I noticed this too.  https://github.com/kdavie/yammer.net/pull/4
